### PR TITLE
Add support for generic objects

### PR DESCRIPTION
**Pull request by idan-at**

### CODE REVIEW

**Comment by agankarin** [comment]
@idan-at how this change would affect the `tern` & `dts` compilation? What about the viewer?

**Review by agankarin — CHANGES_REQUESTED** [review]
Please add tests(maybe also support?) to `docworks-tern` & `docworks-dts`.
Also, please verify that this change doesn't break the viewer

**Comment by agankarin** [comment]
@idan-at we need to make sure this change won't generate docworks `service.json` that will break the viewer/dts/tern models...

**Comment by idan-at** [comment]
@agankarin not sure I'm following. This just adds the support in docworks model, but since we won't generate this structure in jsdoc just yet, this has no effect on tern/dts/viewer. What am I missing?

**Comment by agankarin** [comment]
@idan-at how can you be sure that no one else would add this jsdoc syntax? 
If you change the service.json schema(even if you currently not use it, but someone else might do), you have to make sure you don't break any of the customers.
Also, if none of the customers know how to deal with the new schema, what is the goal of this change?

**Comment by idan-at** [comment]
About the usage - if this still breaks stuff, people won't use it :)

The goal is to split to work to little chunks so this task won't be a "large" task, but some small ones that I'll be able to complete during my other tasks

**Comment by agankarin** [comment]
Docworks is an open-source project, we can't release a feature that might break docworks itself and assume that if it's a bug, then people won't use it.
Every new ability we add to docworks, we add it to the entire docworks(in this case `docworks-tern` & `docworks-dts` and also making sure the viewer handles this change properly)

**Pull request closed without merging**
